# -*- coding: utf-8 -*-
"""resume_analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HTKPCjJIDfCDQFOBin8JAzLaE4_6nxrm
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Input
resume_text = input("Enter your Resume:\n").lower()
job_text = input("Enter Job Description:\n").lower()

# TF-IDF similarity
vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform([resume_text, job_text])
score = cosine_similarity(vectors[0], vectors[1])[0][0]

print("\nMatch Score:", round(score * 100, 2), "%")

# 🔥 Predefined skill list
skills = [
    "python", "machine learning", "deep learning", "nlp",
    "data analysis", "sql", "tensorflow", "pandas",
    "numpy", "scikit-learn", "ai", "statistics"
]

resume_text = resume_text.lower()
job_text = job_text.lower()

matching_skills = []
missing_skills = []

for skill in skills:
    if skill in job_text:
        if skill in resume_text:
            matching_skills.append(skill)
        else:
            missing_skills.append(skill)

print("\nMatching Skills:")
for skill in matching_skills:
    print("-", skill)

print("\nMissing Skills:")
for skill in missing_skills:
    print("-", skill)
print("\nMatching Skills:")
for skill in list(matching_skills)[:10]:
    print("-", skill)

print("\nMissing Skills:")
for skill in list(missing_skills)[:10]:
    print("-", skill)

